name: flutter_fca
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  provider: ^6.0.5
  go_router: ^14.6.1
  flutter_easyloading: ^3.0.5
  dio: ^5.1.1
  http: ^1.2.2
  cupertino_icons: ^1.0.2
  pretty_dio_logger: ^1.4.0
  get_it: ^7.2.0

  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.16
  intl: ^0.20.2
  font_awesome_flutter: ^10.8.0
  package_info_plus: ^8.3.0
  shimmer: ^3.0.0
  uuid: ^4.5.1
  modal_bottom_sheet: ^3.0.0
  file_picker: ^9.0.2
  flutter_pdfview: ^1.4.0
  image_picker: ^1.1.2
  syncfusion_flutter_pdfviewer: ^28.2.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.8
  mocktail: ^1.0.3
  network_image_mock: ^2.0.1
  integration_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
